version: "3.9"

services:

  db:
    image: postgres:15.3
    container_name: ${DB_HOST}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    networks:
      - master_of_pong
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure

  pg_admin:
    image: dpage/pgadmin4
    container_name: pg_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - master_of_pong
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    image: backend
    build: ./backend/
    container_name: backend
    depends_on:
      - db
    restart: on-failure
    networks:
      - master_of_pong
    ports:
      - "5000:5000"
    environment:
      DB_HOST: ${DB_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      API_UID: ${API_UID}
      SECRET: ${SECRET}
    volumes:
      - type: bind
        source: ./backend/nest-user-api/
        target: /backend

  frontend:
    image: frontend
    build: ./frontend/
    container_name: frontend
    depends_on:
      - db
      - backend
    restart: on-failure
    networks:
      - master_of_pong
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    volumes:
      - type: bind
        source: ./frontend/app
        target: /frontend

volumes:
  db_volume:
    driver: local

networks:
  master_of_pong:
    name: master_of_pong
    driver: bridge
