version: '3.9'

services:

  db:
    image: postgres:15.3
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESS_DATABASE: $(POSTGRESS_DATABASE)
    volumes:
       - db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure

  backend:
    image: backend
    build: ./backend/
    container_name: backend
    depends_on:
      - db
    restart: on-failure
    networks:
      - master_of_pong
    ports:
      - "4242:4242"

  frontend:
    image: frontend
    build: ./frontend/
    container_name: frontend
    depends_on:
      - db
    restart: on-failure
    networks:
      - master_of_pong
    ports:
      - "3000:3000"

volumes:
    db_volume:
      driver: local

networks:
  master_of_pong:
    name: master_of_pong
    driver: bridge
