version: '3.9'

services:
  
  backend:
    image: backend
    build:
      context: ./backend
      args:
        - BASE_BACKEND_IMAGE_NAME=${BASE_FRONTEND_IMAGE_NAME}
        - BASE_BACKEND_IMAGE_TAG=${BASE_FRONTEND_IMAGE_TAG}
    container_name: backend
    ports:
      - 4000:4000
  
  frontend:
    image: frontend
    build:
      context: ./frontend
      args:
        - BASE_FRONTEND_IMAGE_NAME=${BASE_FRONTEND_IMAGE_NAME}
        - BASE_FRONTEND_IMAGE_TAG=${BASE_FRONTEND_IMAGE_TAG}
    container_name: frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    # restart: on-failure
    # networks:
    #   - nirvana
    # volumes:
     

# networks:
#   inception:
#     name: nirvana
#     driver: bridge